github: []  # Optional: Add GitHub sponsor usernames
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom:
  - 'https://wa.me/40736676893?text=Hello%20Raven%2C%20I%20want%20to%20support%20your%20project'
  - 'https://tinyurl.com/bdeztsjt'         # 🪐 Raven Bots
  - 'https://tinyurl.com/2hffahu2'         # 🪙 Raven Bots Casino
  - 'https://tinyurl.com/5cfrapju'         # 🫧 Raven Bots Support
